#!/usr/bin/env bash
set -euo pipefail
base="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
pipeline="${base}/pipelines/managed/python-sdist-mirror/python-sdist-mirror.yaml"
prepare="${base}/tasks/managed/prepare-lightwell-release-inputs/prepare-lightwell-release-inputs.yaml"
signer="${base}/tasks/managed/sign-lightwell-release/sign-lightwell-release.yaml"
verifier="${base}/tasks/managed/verify-lightwell-release/verify-lightwell-release.yaml"
materializer="${base}/tasks/managed/materialize-lightwell-carrier/materialize-lightwell-carrier.yaml"
grep -q 'name: taisceImage' "${pipeline}"
grep -q 'value: \$(params.taisceImage)' "${pipeline}"
grep -q 'https://github.com/konflux-lightwell/taisce-cuan.git' "${pipeline}"
grep -q 'source_registry' "${prepare}"
grep -q 'acquired_artifact.sha256' "${prepare}"
grep -q 'rhtl-response.json' "${prepare}"
grep -q 'provenance-response.bin' "${prepare}"
grep -q 'rhtl_response_sha256' "${prepare}"
grep -q 'rhtl-response.json digest does not match' "${prepare}"
grep -q 'metadata.dsse.json' "${signer}"
grep -q 'provenance.dsse.json' "${signer}"
grep -q 'cosign attest-blob --key "${key}" --type' "${signer}"
grep -q 'test ! -L "${origin}"' "${signer}"
grep -q 'test ! -L "${transform}"' "${signer}"
grep -q 'test ! -L "${archive}"' "${signer}"
grep -q 'reject_symlink' "${signer}"
grep -q 'test -z "$(find "${root}" -type l' "${signer}"
grep -q 'test ! -L "${root}/.lightwell"' "${signer}"
grep -q 'test -f "${key}" && test -s "${key}"' "${signer}"
grep -q 'test "$(readlink -- "${key}")" = "..data/cosign.key"' "${signer}"
grep -q 'signing_mount_realpath=' "${signer}"
grep -q 'key_realpath=' "${signer}"
grep -q 'realpath -e' "${signer}"
grep -q -- '--type https://slsa.dev/provenance/v1' "${signer}"
grep -q -- '--type lightwell-metadata' "${signer}"
grep -q -- '--type https://slsa.dev/provenance/v1' "${verifier}"
grep -q -- '--type lightwell-metadata' "${verifier}"
grep -q 'lightwell.catalog-binding' "${signer}"
grep -q 'cosign.pub' "${verifier}"
grep -q 'readOnly: true' "${verifier}"
grep -q 'cmp -s' "${verifier}"
grep -q 'status:200' "${signer}"
grep -q 'path:$p,sha256:$s,url:$u,status:200' "${signer}"
grep -q -- '--arg p "provenance-response.bin"' "${signer}"
grep -q 'response_sha=.*sha256sum.*raw' "${signer}"
grep -q 'copy_evidence "${raw}" "${root}/provenance-response.bin"' "${signer}"
grep -q 'copy_evidence "${raw}" "${root}/.lightwell/provenance-response.bin"' "${signer}"
grep -q 'ln -- "${tmp}" "${target}"' "${signer}"
grep -q 'test ! -e "${target}"' "${signer}"
grep -q 'test "${target_sha}" = "${response_sha}"' "${signer}"
# Version matching is pinned to major 3; v30 and v300 must not be accepted as v3.
version_re='(^|[[:space:]])v?3([.][0-9]+)?([[:space:]]|$)'
printf '%s\n' v3 v3.1 3 3.2 | grep -Eq "${version_re}"
! printf '%s\n' v30 v300 30 3.10.1 | grep -Eq "${version_re}"
grep -Fq "grep -Eq '(^|[[:space:]])v?3([.][0-9]+)?([[:space:]]|$)'" "${signer}"
! grep -q 'params.cosignVersion' "${signer}"
grep -q "grep -Eq '(^|\[\[:space:\]\])v?3" "${signer}"
grep -q 'os.fsync(target.fileno())' "${materializer}"
grep -q 'os.fsync(dir_fd)' "${materializer}"
grep -q 'os.unlink(tmp)' "${materializer}"
# Raw evidence is copied without re-signing and transparency logging remains enabled.
grep -q 'cosign attest-blob.*metadata.*--tlog-upload=true' "${signer}"
! grep -q -- '--tlog-upload=false' "${signer}"
! grep -q 'jq --arg p ".lightwell/provenance-response.bin"' "${signer}"
grep -q 'test -s "${root}/.lightwell/provenance-response.bin"' "${verifier}"
# All three binding variants must dispatch to their own evidence contract.
grep -q "has(\"provenance_dsse\")" "${verifier}"
grep -q "has(\"upstream_provenance_response\")" "${verifier}"
grep -q 'index_response.path' "${verifier}"
grep -q 'test ! -e "${root}/provenance-response.bin"' "${verifier}"
grep -q 'test ! -e "${root}/rhtl-response.json"' "${verifier}"
# PyPI materialization is explicitly response-free, regardless of provenanceResponsePath.
materializer="${base}/tasks/managed/materialize-lightwell-carrier/materialize-lightwell-carrier.yaml"
grep -q 'PyPI provenance is generated and verified as DSSE' "${materializer}"
! sed -n '/pypi.org)/,/rhtl)/p' "${materializer}" | grep -q 'copy_one.*provenanceResponsePath'
! sed -n '/pypi.org)/,/rhtl)/p' "${materializer}" | grep -q 'valid_provenance_url'
! sed -n '/- name: verify-release/,/- name: push-source/p' "${pipeline}" | grep -q 'name: sdistPath'
grep -q 'gitSecretName' "${pipeline}"
grep -q 'gitlabUrl' "${pipeline}"
! grep -q 'sourceOriginType' "${pipeline}"
! grep -q 'verified_sha256' "${prepare}"
! grep -Eiq 'insecure|skip-tlog|disable-tls|IGNORE_REKOR.*true' "${signer}"
