#!/usr/bin/env bash
set -euo pipefail
base="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
pipeline="${base}/pipelines/managed/python-sdist-mirror/python-sdist-mirror.yaml"
prepare="${base}/tasks/managed/prepare-lightwell-release-inputs/prepare-lightwell-release-inputs.yaml"
signer="${base}/tasks/managed/sign-lightwell-release/sign-lightwell-release.yaml"
verifier="${base}/tasks/managed/verify-lightwell-release/verify-lightwell-release.yaml"
grep -q 'name: taisceImage' "${pipeline}"
grep -q 'value: \$(params.taisceImage)' "${pipeline}"
grep -q 'https://github.com/konflux-lightwell/taisce-cuan.git' "${pipeline}"
grep -q 'source_registry' "${prepare}"
grep -q 'acquired_artifact.sha256' "${prepare}"
grep -q 'rhtl-response.json' "${prepare}"
grep -q 'provenance-response.bin' "${prepare}"
grep -q 'metadata.dsse.json' "${signer}"
grep -q 'provenance.dsse.json' "${signer}"
grep -q 'lightwell.catalog-binding' "${signer}"
grep -q 'cosign.pub' "${verifier}"
grep -q 'readOnly: true' "${verifier}"
grep -q 'cmp -s' "${verifier}"
grep -q 'status:200' "${signer}"
grep -q 'path:$p,sha256:$s,url:$u,status:200' "${signer}"
grep -q -- '--arg p "provenance-response.bin"' "${signer}"
grep -q 'cp --preserve=all "${raw}" "${root}/provenance-response.bin"' "${signer}"
grep -q 'cp --preserve=all "${raw}" "${root}/.lightwell/provenance-response.bin"' "${signer}"
! grep -q 'jq --arg p ".lightwell/provenance-response.bin"' "${signer}"
grep -q 'test -s "${root}/.lightwell/provenance-response.bin"' "${verifier}"
! sed -n '/- name: verify-release/,/- name: push-source/p' "${pipeline}" | grep -q 'name: sdistPath'
grep -q 'gitSecretName' "${pipeline}"
grep -q 'gitlabUrl' "${pipeline}"
! grep -q 'sourceOriginType' "${pipeline}"
! grep -q 'verified_sha256' "${prepare}"
! grep -Eiq 'insecure|skip-tlog|disable-tls|IGNORE_REKOR.*true' "${signer}"
