#!/usr/bin/env bash
set -euo pipefail
base="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
pipeline="${base}/pipelines/managed/python-sdist-mirror/python-sdist-mirror.yaml"
prepare="${base}/tasks/managed/prepare-lightwell-release-inputs/prepare-lightwell-release-inputs.yaml"
signer="${base}/tasks/managed/sign-lightwell-release/sign-lightwell-release.yaml"
verifier="${base}/tasks/managed/verify-lightwell-release/verify-lightwell-release.yaml"
grep -q '53ea1359c066e28463ae7a49234d2ccc84e59c4f' "${pipeline}"
grep -q 'https://github.com/konflux-lightwell/taisce-cuan.git' "${pipeline}"
grep -q 'default: ""' "${pipeline}"
grep -q 'source_registry' "${prepare}"
grep -q 'verified_sha256' "${signer}"
grep -q 'RHTL publication blocked' "${signer}"
grep -q 'metadata.dsse.json' "${signer}"
grep -q 'provenance.dsse.json' "${signer}"
grep -q 'lightwell.catalog-binding' "${signer}"
grep -q 'cmp -s' "${verifier}"
grep -q -- '--signature' "${verifier}"
grep -q 'gitSecretName' "${pipeline}"
grep -q 'gitlabUrl' "${pipeline}"
! grep -q 'lightwell-signer-authorization' "${prepare}"
! grep -Eiq 'insecure|skip-tlog|disable-tls|IGNORE_REKOR.*true' "${signer}"
